# Generated by Django 3.1.4 on 2021-10-29 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendREST', '0002_auto_20211017_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='items',
            new_name='item',
        ),
    ]
